name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  Building:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Build app on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Use Node.js v22
        uses: actions/setup-node@v4
      - name: Install Dependencies
        run: npm ci
      - name: Build app
        run: npm run build -- --publish never
        if: github.event_name == 'pull_request'
      - name: Build app and publish
        run: npm run build -- --publish always
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name != 'pull_request'
